### ISSUE TITLE
Leds to see active/sticky faults on motors

### ISSUE THREAD

**Issue by GalexY727** [Patribots4738/Crescendo2024#237]
## User Story
We are eventually going to have problems with motors. We can have the leds tell us which motors are // working and which ones aren't so we don't always have to go into URCL or rev hardware client.

## Acceptance Criteria
- [ ] Create a system which maps an led strip to all motors and displays if there is any fault on the motor.
- [ ] Use the same LED patterns as REV so we can recognize the error without having to look at the spark. 
- [ ] Have a new indicator for when a parameter doesn't get set properly inside of SafeSpark (green/gold flash?)
- [ ] Map each CAN ID to an led, and have 19 leds total for all 17 motors * gyroscope (gyro has two leds on it)
- [ ] Use the led patterns from CTRE to communicate errors on the gyro

**Comment by Jacob1010-h** [comment]
I feel like this could be completed? not before worlds though, so for now I'm going to close all issues to #233 .
