### ISSUE TITLE
Setpoint Generator

### ISSUE THREAD

**Issue by Jacob1010-h** [Patribots4738/Crescendo2024#267]
## User Story
In different areas, while driving the robot, we can notice some slippage issues with the robot. This code is directly "inspired" from 254's code in 2023. This is how they discribe their class.

> Takes a prior setpoint (ChassisSpeeds), a desired setpoint (from a driver, or from a path follower), and outputs a new setpoint that respects all of the kinematic constraints on module rotation speed and wheel velocity/acceleration. By generating a new setpoint every iteration, the robot will converge to the desired setpoint quickly while avoiding any intermediate state that is kinematically infeasible (and can result in wheel slip or robot heading drift as a result).

## Acceptance Criteria
- [ ] Must work in sim, and demonstraits a limit in slippage as we move our swerve modules. 
- [ ] Must be clean code (pls) (this is for everyone's sanity later on)
- [ ] Maybe go to sleep before 11 cause I need some

**Comment by Jacob1010-h** [comment]
How important would you say that this gets done btw? I'd like to assign a priority for the upcoming competition

**Comment by GalexY727** [comment]
If the math works, I would be fine running it at comp for the first time. But, if there are issues with the behaviors, then it's not worth running.

**Comment by GalexY727** [comment]
Our first practice match will be without it as a first basis, and if we get to run another match with the same auto on the same alliance then i'd be fine running the new code to see if it works... but i might be in the wrong for thinking that way right before a competition.

**Comment by GalexY727** [comment]
I would say at this point I think we are too close to competition to be introducing new features like this in the code. Hopefully we can see some benefits from it next year 🥲
