### ISSUE TITLE
Final code cleanup for public release

### ISSUE THREAD

**Issue by GalexY727** [Patribots4738/Crescendo2024#269]
Let's make this repository nice and spiffy

- [x] Add documentation to complicated methods/code blocks
- [x] Clean up all those TODOs
- [x] Update pictures in README to use the new CAD
- [x] Remove any of the editable links of the tldraws, or at least make those ones private
- [x] #272
- [x] Read through robotContainer one last time to ensure that the flow of the code is smooth and is intuitive.

**Comment by Jacob1010-h** [comment]
This has been reviewed and is ready to go. Whether we decide to hold one last competition will determine the completion of this issue.

**Comment by GalexY727** [comment]
whoops. this gets resolved when #277 does.
