### ISSUE TITLE
Speed up passing by reducing deadbands

### ISSUE THREAD

**Issue by GalexY727** [Patribots4738/Crescendo2024#276]
## User Story
If we are passing, the last thing we want is for the pass to take the same amount of time as coming back to shoot. Let's make the RPM (and more importantly, the swerve theta deadband) more when we pass so we can get the green light faster.

## Acceptance Criteria
- [ ] complete user story

**Comment by GalexY727** [comment]
another possible solution would to just shoot if rpm > 1500 and angle > 45 or some threshold

**Comment by derp00monsta** [comment]
How does your controls work? After you run preparePassCommand, what do you press to index the note to the shooter?

**Comment by GalexY727** [comment]
it'll run a noteToShoot after readyToShoot is true, but that's pretty much the same thing as what rudy said

**Comment by derp00monsta** [comment]
@GalexY727 do  you want to have an upper limit for shooting that is different than the lower limit?

**Comment by derp00monsta** [comment]
and what is the best way to define whether we are shooting or passing?

**Comment by GalexY727** [comment]
we can go off of the swerve's position to see whether we are shooting or passing, it would be the same booleanSupplier as the Commands.either for the driver's rightStick binding. This is referencing the single-driver branch, for the record. I recommend you work off of that one instead of main. Anyhow, if we are in the zone that defines a pass to be used rather than a shot, we could just change the deadbands used to evaluate shootWhenReady.

**Comment by GalexY727** [comment]
> @GalexY727 do  you want to have an upper limit for passing that is different than the lower limit?

What lower limit are you talking about?

**Comment by derp00monsta** [comment]
> > @GalexY727 do  you want to have an upper limit for passing that is different than the lower limit?
> 
> What lower limit are you talking about? 

What I mean is having an asymmetrical deadband. Instead of allowing the rpm to be 100 under or over the desired rpm, should we allow to to be 200 over and 100 under the desired? Similar to what you said about letting the current rpm be any amount greater than the desired, but what if we let it be too high and it shoots a note out of the field?

**Comment by GalexY727** [comment]
No, just making the whole thing larger would be fine

**Comment by GalexY727** [comment]
That's only because the shooter starts stopped when we are preparing to pass, so we don't have to worry about it being so much over. Plus, it slows down fast if that's its goal and it was over for any reason

**Comment by derp00monsta** [comment]
what do you want the passing deadband to be?

**Comment by GalexY727** [comment]
iijaushudh, liek 150
