### ISSUE TITLE
The trifetca merge

### ISSUE THREAD

**Issue by GalexY727** [Patribots4738/Crescendo2024#277]
## User Story
We have valuable changes on the single-driver branch, #269's branch, and main, all of which we want on main... in some way. While I don't feel exactly comfortable pushing the changes to the file structure introduced by #269 into main, I warmly welcome the README changes and think that those are still valuable to cherry-pick.

## Acceptance Criteria
- [x] #278
- [x] cherry-pick readme changes and other qol changes from #269 and put them onto the branch for this issue
  - edit: i just put them into single-driver
- [x] Make a pr for this branch going into single-driver, which will eventually go to main from single-driver.
- [ ] Fix all hyperlinks inside of README (for files) to actually go to the location of the file. We have shifted around our folders far too many times for this to keep its accuracy,

**Comment by Jacob1010-h** [comment]
I think that I would like to take up the single driver Todo, I already have a good idea of how I want to do it, it should also clean up our bindings in general

**Comment by GalexY727** [comment]
just so you are aware going into this the single driver bindings are completed on single-driver's branch, but they are hardcoded so there is no going back as of now. The hope is to make it an option in constants or something similar.

**Comment by Jacob1010-h** [comment]
So to clarify, we want to be able to swap between the bindings on the single driver branch and the bindings on main?

**Comment by Jacob1010-h** [comment]
This will be taken a look at again.. after worlds
