### ISSUE TITLE
Elastic support

### ISSUE THREAD

**Issue by GalexY727** [Patribots4738/Crescendo2024#298]
## User Story
A driver UI that doesn't subscribe to everything on NT

## Acceptance Criteria
- [x] Research Elastic and what you can do with it
- [ ] Create a UI with elastic that has a large timer, an auto selector, and a field2d
  - If possible, a swerve visualizer would be cool too

**Comment by Oliver-Cushman** [comment]
I'm just gonna go ahead and swoop this out from under your nose Tina because I want I want I want

**Comment by GalexY727** [comment]
> I'm just gonna go ahead and swoop this out from under your nose Tina because I want I want I want

bro has the right mindset
