### ISSUE TITLE
Component Unit Tests

### ISSUE THREAD

**Issue by GalexY727** [Patribots4738/Crescendo2024#99]
## User Story
With the closure of #27, we need to make sure that each and every subsystem is realisitally able to move. We are going to be getting an alpha bot very soon, and our number one priority should be to not break anything too on our first code run. I think it's possible for it to work first try, so let's find out how to get that done
## Acceptance Criteria
- [x] Each component needs to be able to move in sim. Our motors are capible of running in simulation, we just need to make sure we are logging them correctly and that our position conversion factors make the movement reasonable.
  - [x] Doubling off of the above, we need to have soft stops to limit our components. A soft stop is a limit in the code that stops the motor from going any further, even though it physically might be able to. The easiest way to enforce a soft stop is by using `MathUtil.clamp(value, min, max)`, with constants representing our min and max value.
- [x] Gear ratios
  - Yeah. they exist. We need constants in the code for them so that we can run things like setPositionConversionFactor or setVelocityConversionFactor and all we need to do is plug in the required value to get that done. Notice that #98 outputs in meters for the climb's desired height. The goal for this bullet is for us to turn meters into motor rotations. 
- [x] Unit tests
  - Each subsystem should have a "unit test" that it runs when we initially get the robot to SLOWLY (think around 10 seconds) move it from one end of its limit to another, just so that we can test things like negative signs without telling the motor to go full throttle. 
- [x] PID (where applicable)
  - For motors that run a PID controller (shooter, elevator, climb) we need to have those constants set to a reasonable gain before telling the motor to move at all. I recommend starting with a `P` of `0.01` and an `I` and `D` of `0`. PID can really easily tell our motor to go faster than we initially intended for it to go.

Thankfully, since we have sim, we are able to ask the motor what it thinks its simulated position or velocity is, which is a great start to seeing if our logic is telling it to do the right things or not.

**Comment by Jacob1010-h** [comment]
> While JUnit tests are really powerful, I think that they are more attuned to a public repository rather than a private one like our robot. We know that most of our code works because we generally test in sim before PRing, and that is our substitution of a JUnit test. Most of these checkboxes are kind-of done, but I want this issue to serve as a final to-do list to check off before we click enable on our first real robot deployment. The last thing we want to do is break a falcon (cough cough supernurds) ![](https://camo.githubusercontent.com/052ae7a2c057c8dcc515532dab8a4ff00b4727368e302c23fe544f3dbf629954/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f313034333433383839393536373030313632312f313230323830333031303234323334373031392f494d475f363334392e6a70673f65783d36356365633839382669733d363562633533393826686d3d6361343630376362366638353631323562316564313362303964323632663764623632313135353563313130336162653138306534303534386237316465653826)

I feel like this is no longer the case, after working with them for #288, I think that for testing math, JUnits are very powerful. For general application though, sim is still da best.

**Comment by GalexY727** [comment]
> > While JUnit tests are really powerful, I think that they are more attuned to a public repository rather than a private one like our robot. We know that most of our code works because we generally test in sim before PRing, and that is our substitution of a JUnit test. Most of these checkboxes are kind-of done, but I want this issue to serve as a final to-do list to check off before we click enable on our first real robot deployment. The last thing we want to do is break a falcon (cough cough supernurds) ![](https://camo.githubusercontent.com/052ae7a2c057c8dcc515532dab8a4ff00b4727368e302c23fe544f3dbf629954/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f313034333433383839393536373030313632312f313230323830333031303234323334373031392f494d475f363334392e6a70673f65783d36356365633839382669733d363562633533393826686d3d6361343630376362366638353631323562316564313362303964323632663764623632313135353563313130336162653138306534303534386237316465653826)
> 
> I feel like this is no longer the case, after working with them for #288, I think that for testing math, JUnits are very powerful. For general application though, sim is still da best.

Although that math was shown to work, #288 still failed the "unit test" of running it in sim and seeing if the output was as expected. While this did come down to tuning constants, the JUnit files would be fully encapsulated in testing the entire functionality in sim. Again, not saying JUnits are worthless, but I don't think that they are necessary when we look at the other resources we have access to.

**Comment by Jacob1010-h** [comment]
> > > While JUnit tests are really powerful, I think that they are more attuned to a public repository rather than a private one like our robot. We know that most of our code works because we generally test in sim before PRing, and that is our substitution of a JUnit test. Most of these checkboxes are kind-of done, but I want this issue to serve as a final to-do list to check off before we click enable on our first real robot deployment. The last thing we want to do is break a falcon (cough cough supernurds) ![](https://camo.githubusercontent.com/052ae7a2c057c8dcc515532dab8a4ff00b4727368e302c23fe544f3dbf629954/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f313034333433383839393536373030313632312f313230323830333031303234323334373031392f494d475f363334392e6a70673f65783d36356365633839382669733d363562633533393826686d3d6361343630376362366638353631323562316564313362303964323632663764623632313135353563313130336162653138306534303534386237316465653826)
> > 
> > 
> > I feel like this is no longer the case, after working with them for #288, I think that for testing math, JUnits are very powerful. For general application though, sim is still da best.
> 
> Although that math was shown to work, #288 still failed the "unit test" of running it in sim and seeing if the output was as expected. While this did come down to tuning constants, the JUnit files would be fully encapsulated in testing the entire functionality in sim. Again, not saying JUnits are worthless, but I don't think that they are necessary when we look at the other resources we have access to.

Agreed, it's better to test via implementation then with fake data that didn't prove it would work with my implementation. But then again, I probably could've written my test differently with that In mind.

I think that this is the major separating factor: to make junit tests valuable, you need to build with them in mind. Because that wasn't a concern for us, Junits prove useless for us
